name: flutter_webview_1
description: "A new Flutter project."
# 다음 줄은 실수로 pub.dev에 `flutter pub publish`를 사용하여 패키지가 게시되는 것을 방지합니다.
# 비공개 패키지의 경우 이 방법을 권장합니다.
publish_to: "none" # pub.dev에 게시하려면 이 줄을 제거하세요

# 다음은 애플리케이션의 버전과 빌드 번호를 정의합니다.
# 버전 번호는 1.2.43과 같이 점으로 구분된 세 개의 숫자입니다
# 그 뒤에 선택적으로 +로 구분된 빌드 번호가 올 수 있습니다.
# 버전과 빌드 번호는 각각 --build-name과 --build-number를 지정하여
# flutter 빌드에서 재정의할 수 있습니다.
# Android에서는 build-name이 versionName으로 사용되고 build-number는 versionCode로 사용됩니다.
# Android 버전 관리에 대한 자세한 내용은 https://developer.android.com/studio/publish/versioning 참조
# iOS에서는 build-name이 CFBundleShortVersionString으로 사용되고 build-number는 CFBundleVersion으로 사용됩니다.
# iOS 버전 관리에 대한 자세한 내용은
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html 참조
# Windows에서는 build-name이 제품 및 파일 버전의 주 버전, 부 버전, 패치 부분으로 사용되고
# build-number는 빌드 접미사로 사용됩니다.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# 의존성은 패키지가 작동하기 위해 필요한 다른 패키지들을 지정합니다.
# 패키지 의존성을 최신 버전으로 자동 업그레이드하려면
# `flutter pub upgrade --major-versions`를 실행하는 것을 고려해보세요. 또는
# 아래의 버전 번호를 pub.dev에서 사용 가능한 최신 버전으로 수동으로 업데이트할 수 있습니다.
# 사용 가능한 새 버전이 있는 의존성을 확인하려면 `flutter pub outdated`를 실행하세요.
dependencies:
  flutter:
    sdk: flutter

  # 다음은 애플리케이션에 Cupertino Icons 폰트를 추가합니다.
  # iOS 스타일 아이콘을 위해 CupertinoIcons 클래스와 함께 사용하세요.
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  kakao_flutter_sdk: ^1.9.7+3
  sign_in_with_apple: ^6.1.4
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1

  webview_flutter_android: any
  webview_flutter_wkwebview: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # 아래의 "flutter_lints" 패키지는 좋은 코딩 관행을 장려하기 위한
  # 권장 린트 세트를 포함합니다. 패키지에서 제공하는 린트 세트는
  # 패키지 루트에 있는 `analysis_options.yaml` 파일에서 활성화됩니다.
  # 특정 린트 규칙을 비활성화하고 추가 규칙을 활성화하는 방법에 대한
  # 정보는 해당 파일을 참조하세요.
  flutter_lints: ^4.0.0

# 이 파일의 일반적인 Dart 부분에 대한 정보는
# 다음 페이지를 참조하세요: https://dart.dev/tools/pub/pubspec

# 다음 섹션은 Flutter 패키지에 특화되어 있습니다.
flutter:
  # 다음 줄은 Material Icons 폰트가 애플리케이션에
  # 포함되도록 하여 material Icons 클래스의 아이콘을
  # 사용할 수 있게 합니다.
  uses-material-design: true

  # 애플리케이션에 에셋을 추가하려면 다음과 같이 assets 섹션을 추가하세요:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 이미지 에셋은 하나 이상의 해상도별 "변형"을 참조할 수 있습니다.
  # 자세한 내용은 https://flutter.dev/to/resolution-aware-images 참조

  # 패키지 의존성에서 에셋을 추가하는 방법에 대한 자세한 내용은
  # https://flutter.dev/to/asset-from-package 참조

  # 애플리케이션에 사용자 정의 폰트를 추가하려면 여기 "flutter" 섹션에
  # fonts 섹션을 추가하세요. 이 목록의 각 항목은 폰트 패밀리 이름을
  # 가진 "family" 키와 폰트의 에셋 및 기타 설명자를 제공하는 목록을
  # 가진 "fonts" 키를 가져야 합니다. 예를 들어:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 패키지 의존성의 폰트에 대한 자세한 내용은
  # https://flutter.dev/to/font-from-package 참조
